pipeline {
  agent any 
  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/DiviPavanKumar/CICD.git'
      }
    }

    stage('Build and Test') {
      steps {
        sh '''
        cd spring-boot-app 
        mvn clean package
        docker run -d -p 9090:9090 your-spring-boot-image
        '''
      }
    }
  }
}
